### ISSUE TITLE
Installation instructions need to be updated

### ISSUE THREAD

**Issue by chetstone** [lunixbochs/vtclean#12]
When I try `go get github.com/lunixbochs/vtclean/vtclean`

I get:
```
go get: installing executables with 'go get' in module mode is deprecated.
	Use 'go install pkg@version' instead.
	See 'go help get' and 'go help install' for more information.
```
using a recent go: `go version devel +f3ce010b33 Thu Nov 19 21:51:34 2020 +0000 darwin/arm64`

As a workaround I found an older version of go on another machine `go version go1.15.5 darwin/amd64`

and it worked great for my one-off task. 

I'm not a go user, so this is all I can share..

**Comment by lunixbochs** [comment]
I think it's go install ***@***.***

**Comment by chetstone** [comment]
I get:
```
$ go install github.com/lunixbochs/vtclean/vtclean
no required module provides package github.com/lunixbochs/vtclean/vtclean: working directory is not part of a module
```

**Comment by lunixbochs** [comment]
Sorry looks like github censored my command as an email address, because I sent it over email.

Try this: `go install github.com/lunixbochs/vtclean/vtclean@v1.0.0`

**Comment by chetstone** [comment]
Interesting, I didn't know they did that. 

Yes, that works. Sending PR.

Thanks!
